services:
  bot:
    build: .
    restart: unless-stopped
    container_name: professor_bot
    env_file:
      - .env
    networks:
      - professor-bot
    volumes:
      - ./data:/app/data

networks:
  professor-bot:
    external: true
